- name: Verify RoboShop Stack Health
  hosts: localhost
  vars:
    base_domain: "prashum.online"
    
    # DBs only need Port Checks
    databases:
      mongodb: 27017
      redis: 6379
      mysql: 3306
      rabbitmq: 5672

    # Apps need HTTP Health Checks
    apps:
      catalogue: 8080
      user: 8080
      cart: 8080
      shipping: 8080
      payment: 8080
      frontend: 80

  tasks:
    - name: "STEP 1: Verify Database Ports"
      ansible.builtin.wait_for:
        host: "{{ item.key }}-dev.{{ base_domain }}"
        port: "{{ item.value }}"
        state: started
        timeout: 10
      loop: "{{ databases | dict2items }}"

    - name: "STEP 2: Verify App Health Endpoints"
      ansible.builtin.uri:
        url: "http://{{ item.key }}-dev.{{ base_domain }}:{{ item.value }}{{ '/health' if item.key != 'frontend' else '' }}"
        status_code: 200
      register: result
      until: result.status == 400
      retries: 12
      delay: 5
      loop: "{{ apps | dict2items }}"
